"""Initial migration

Revision ID: f6b1a9a4039f
Revises: 
Create Date: 2026-06-12 15:26:30.413323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6b1a9a4039f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('slug')
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('unique_favorite')
        batch_op.create_unique_constraint('unique_user_product_favorite', ['user_id', 'product_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('order_items_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_tracking_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index('order_number')
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('notes')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_condition', sa.Enum('new', 'second-hand', name='product_conditions'), nullable=True))
        batch_op.add_column(sa.Column('sold_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index('slug')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)
        batch_op.drop_constraint('products_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('condition')

    with op.batch_alter_table('seller_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negotiated_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('seller_submissions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('seller_submissions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('seller_submissions_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('submission_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('testimonials_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index('email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_unique_constraint(None, ['reset_token'])
        batch_op.create_unique_constraint(None, ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('email', ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('last_login')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('testimonials_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('approved_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('admin_response')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('title')

    with op.batch_alter_table('submission_images', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('display_order')

    with op.batch_alter_table('seller_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('seller_submissions_ibfk_3', 'users', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key('seller_submissions_ibfk_2', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('seller_submissions_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('purchased_at')
        batch_op.drop_column('negotiated_price')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', mysql.ENUM('new', 'second-hand'), server_default=sa.text("'second-hand'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_2', 'users', ['created_by'], ['id'])
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('slug', ['slug'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('sold_at')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_active')
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')
        batch_op.drop_column('weight')
        batch_op.drop_column('sold_count')
        batch_op.drop_column('product_condition')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('alt_text')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.create_index('order_number', ['order_number'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipped_at')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('courier_tracking_url')
        batch_op.drop_column('courier_name')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('transaction_reference')
        batch_op.drop_column('mpesa_checkout_request_id')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_ibfk_2', 'products', ['product_id'], ['id'])
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_product_favorite', type_='unique')
        batch_op.create_index('unique_favorite', ['user_id', 'product_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.create_index('slug', ['slug'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('icon')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('updated_at')

    op.create_table('contacts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
